[project]
name = "fastapi-gemini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "google-generativeai>=0.8.6",
    "pydantic>=2.12.5",
    "uvicorn>=0.40.0",
]
